In [1]:
from IPython.display import Image

- 基于 clustering 的 weights quantization
    - k-means clustering

In [2]:
Image(url='../../imgs/quant-clustering.jpeg', width=400)

In [3]:
import numpy as np
from sklearn.cluster import KMeans

# 原始权重矩阵
weights = np.array([
    [2.09, -0.98, 1.48, 0.09],
    [0.05, -0.14, -1.08, 2.12],
    [-0.91, 1.92, 0, -1.03],
    [1.87, 0, 1.53, 1.49]
])

# K-means聚类
kmeans = KMeans(n_clusters=4)
kmeans.fit(weights.reshape(-1, 1))
cluster_indices = kmeans.predict(weights.reshape(-1, 1)).reshape(weights.shape)
centroids = kmeans.cluster_centers_.flatten()

# 根据质心值排序
sorted_indices = np.argsort(centroids)
sorted_centroids = centroids[sorted_indices]

# 创建索引映射
index_map = {old_idx: new_idx for new_idx, old_idx in enumerate(sorted_indices)}

# 更新量化索引矩阵
new_cluster_indices = np.vectorize(index_map.get)(cluster_indices)

print("重新排序后的量化索引矩阵：\n", new_cluster_indices)
print("重新排序后的质心值：\n", sorted_centroids)

重新排序后的量化索引矩阵：
 [[3 0 2 1]
 [1 1 0 3]
 [0 3 1 0]
 [3 1 2 2]]
重新排序后的质心值：
 [-1.   0.   1.5  2. ]


/home/whaow/anaconda3/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
